config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/songs')

  resources :songs do
    member do
      get 'print'
    end
  end

  resources :audits, only: [:index]

  get 'songs/:id/history', to: 'audits#song_history', as: 'song_history'

  get "about", to: "general#about"
  get "request_song", to: "general#request_song"

  # Authentication
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: 'sessions#error'
  get 'signout', to: 'sessions#destroy', as: 'sign_out'
  get 'signin', to: 'sessions#new', as: 'sign_in'

  namespace :api, defaults: {format: :json} do
    scope :v1 do
      resources :songs

      scope :audits do
        scope :songs do
          get ':id', to: "audits#song_history"
          get '', to: 'audits#songs_history_index'
        end
      end
    end
  end
end

app/models/song.rb
# frozen_string_literal: true

class Song < ApplicationRecord
  audited except: [:lyrics, :view_count]

  include PgSearch::Model
  pg_search_scope(
    :search_by_keywords,
    against: { name: 'A', artist: 'B', lyrics: 'C' },
    using: { tsearch: { any_word: false, prefix: true } }
  )

  VALID_KEYS = Music::MAJOR_KEYS
  VALID_TEMPOS = %w[Fast Medium Slow].freeze
  VALID_CATEGORIES = %w[Special Hymn Christmas].freeze
  MAX_LINE_LENGTH = 47

  before_validation :normalize
  before_save :extract_lyrics
  before_destroy :record_deletion

  validates :name, presence: true, uniqueness: {
    scope: :artist,
    message: "is taken by another song by this artist"
  }
  validates :key, presence: true
  validates :key, inclusion: { in: VALID_KEYS, if: ->(song) { song.key.present? } }
  validates :tempo, presence: true
  validates :tempo, inclusion: { in: VALID_TEMPOS, if: ->(song) { song.tempo.present? } }
  validates :category, inclusion: { in: VALID_CATEGORIES, if: ->(song) { song.category.present? } }
  validates :chord_sheet, presence: true
  validate :line_length, if: ->(song) { song.chord_sheet.present? }
  validates :spotify_uri,
            format: { with: /\Aspotify:track:\w{22}\z/ },
            if: ->(song) { song.spotify_uri.present? }
  validates :bpm, numericality: {
    allow_nil: true,
    only_integer: true,
    greater_than: 0,
    less_than_or_equal_to: 1000
  }

  def to_s
    name_and_artist = artist.blank? ? name : "#{name} by #{artist}"
    "#{name_and_artist} (id: #{id})"
  end

  # include spotify_widget_source and remove spotify_uri when serialized as JSON hash
  # https://blog.arkency.com/how-to-overwrite-to-json-as-json-in-active-record-models-in-rails/
  def as_json(*)
    super.except("spotify_uri").tap do |json_hash|
      json_hash[:spotify_widget_source] = spotify_widget_source
    end
  end

  def spotify_widget_source
    "https://open.spotify.com/embed?uri=#{spotify_uri}" if spotify_uri.present?
  end

  private

  # Titlize fields, remove unnecessary spaces, make headers all caps
  def normalize
    self.name = name.titleize.strip if name

    self.artist = artist.titleize.strip if artist

    if standard_scan
      self.standard_scan = standard_scan.upcase.split.each do |section_abbr|
        section_abbr.concat(".") if section_abbr[-1] != "."
      end.join(" ")
    end

    return unless chord_sheet

    self.chord_sheet = chord_sheet.split("\n").map do |line|
      line = line.upcase if Parser.header_line?(line)
      line.rstrip
    end.join("\n")
  end

  def extract_lyrics
    lyrics = chord_sheet.split("\n").select { |line| Parser.lyrics_line?(line) }
    self.lyrics = lyrics.join("\n")
  end

  # assumes that chord_sheet is not nil
  def line_length
    line_numbers = []
    chord_sheet.split("\n").each_with_index do |line, i|
      line_numbers << (i + 1) if line.rstrip.length > MAX_LINE_LENGTH
    end
    return unless line_numbers.any?

    line_pluralized = 'line'.pluralize(line_numbers.length)
    line_numbers_string = line_numbers.join(',')
    errors.add(:chord_sheet,
               "#{line_pluralized}: #{line_numbers_string} cannot be longer than #{MAX_LINE_LENGTH} characters long")
  end

  def record_deletion
    SongDeletionRecord.create!(
      id:,
      name:
    )
  end
end

app/controllers/api/audits/songs_controller.rb
class API::Audits::SongsController < API::APIController
  DEFAULT_PAGE_SIZE = 20

  def show
    song = Song.find(params[:id])
    # only show 100 most recent audits to prevent DOS
    update_audits = song.audits.updates.limit(100)
    render json: update_audits
  end

  def index
    page_num = params[:page_num] ? params[:page_num].to_i : 1
    page_size = params[:page_size] ? params[:page_size].to_i : DEFAULT_PAGE_SIZE

    audits = Audited.audit_class.order(created_at: :desc)
    audits = audits.where(action: params[:action]) if AuditAction.valid_action?(params[:action])
    matching_audits_count = audits.size

    audits = audits.paginate(page: page_num, per_page: page_size)

    audits_info_list = audits.map do |audit|
      song = Song.find_by(id: audit.auditable_id)
      if song.nil?
        is_deleted = true
        song_name = SongDeletionRecord.find(audit.auditable_id).name
      else
        is_deleted = false
        song_name = song.name
      end
      [audit, song_name, is_deleted]

    end

    render json: API::PaginatedResult(audits_info_list, matching_audits_count, Audited.audit_class.count)
  end
end

app/controllers/api/songs_controller.rb
# frozen_string_literal: true

class API::SongsController < API::APIController
  before_action :require_edit_privileges, only: [:create, :update]
  before_action :require_delete_privileges, only: [:destroy]

  def show
    song = Song.find_by(id: params[:id])
    return head(:not_found) unless song

    case params[:sheet_format]
    when 'nashville'
      Formatter.format_song_nashville(song)
    when 'no_chords'
      Formatter.format_song_no_chords(song)
    else
      Transposer.transpose_song(song, params[:key]) if params[:key].present?
    end

    Song.increment_counter(:view_count, song.id, touch: false)

    render json: song
  end

  def index
    songs = Song

    # perform searching and filtering
    # pg_search requires search_by_keywords to be to run first before anything else
    songs = songs.search_by_keywords(params[:query]) if params[:query].present?
    songs = songs.where(key: params[:key]) if params[:key].present?
    songs = songs.where(tempo: params[:tempo]) if params[:tempo].present?
    songs = songs.where(category: params[:category]) if params[:category].present?
    songs = songs.select('id, artist, tempo, key, name, chord_sheet, spotify_uri, category')
    matching_songs_count = songs.size

    # perform sorting
    songs =
      case params[:sort_by]
      when 'created_at'
        songs.reorder(created_at: :desc)
      when 'name'
        songs.reorder(name: :asc)
      when 'views'
        songs.reorder(view_count: :desc)
      else
        # if search_by_keywords was run, then the results are already sorted by relevance
        songs
      end

    # perform paginate
    page_num = params[:page_num]&.to_i || 1
    page_size = [params[:page_size]&.to_i || DEFAULT_PAGE_SIZE, 500].min
    songs = songs.paginate(page: page_num, per_page: page_size)

    render_paginated_result(songs, matching_songs_count, Song.count)
  end

  def create
    song = Song.new(song_params)
    if song.save
      flash[:success] = "#{song.name} successfully created!"
      render json: song
    else
      render_form_errors("Couldn't save song", song.errors)
    end
  end

  def update
    song = Song.find(params[:id])
    if song.update(song_params)
      render json: song
    else
      render_form_errors("Couldn't edit song", song.errors)
    end
  end

  def destroy
    if Song.destroy_by(id: params[:id]).empty?
      head :not_found
    else
      head :no_content
    end
  end

  private

  def song_params
    params.require(:song)
          .permit(:name, :key, :artist, :tempo, :bpm, :standard_scan, :chord_sheet, :spotify_uri, :category)
  end
end

app/controllers/api/v2/songs_controller.rb
# Songs controller
class API::V2::SongsController < API::V2::APIController
  # GET /
  def index
    render json: @songs
  end

  # POST /
  def create
    render json: Song.create!(song_params), status: :created
  end

  # GET /:id
  def show
    render json: @song
  end

  # PUT /:id
  def update
    @song.update!(song_params)
    render json: @song
  end

  # DELETE /:id
  def destroy
    @song.destroy!
    head :no_content
  end

  def song_params
    params.require(:song)
        .permit(:name, :artist, :key, :tempo, :chord_sheet, :bpm, :spotify_uri)
  end
end

app/controllers/songs_controller.rb
# frozen_string_literal: true

class SongsController < ApplicationController
  before_action :require_edit_privileges, only: [:new, :create, :edit, :update]
  before_action :require_delete_privileges, only: [:destroy]

  SONGS_PER_PAGE_DEFAULT = 10

  def index
    respond_to do |format|
      format.json do
        songs = Song

        # perform searching and filtering
        # pg_search requires search_by_keywords to be to run first before anything else
        search_value = params.dig(:search, :value)
        songs = songs.search_by_keywords(search_value) if search_value.present?
        songs = songs.where(key: params[:key]) if params[:key].present?
        songs = songs.where(tempo: params[:tempo]) if params[:tempo].present?
        songs = songs.where(category: params[:category]) if params[:category].present?
        # get number of matching songs post filtering
        records_filtered = songs.count
        songs = songs.select('id, artist, tempo, key, name, chord_sheet, spotify_uri, category')

        # reorder
        songs = case params[:sort]
                when 'Newest First'
                  songs.reorder(created_at: :desc)
                when 'Most Popular First'
                  songs.reorder(view_count: :desc)
                else
                  # does nothing if search_by_keywords was run, in which case songs are already ordered by relevance
                  songs.order(name: :asc)
                end

        # paginate
        if params[:start].present?
          page_size = (params[:length] || SONGS_PER_PAGE_DEFAULT).to_i
          page_num = (params[:start].to_i / page_size.to_i) + 1

          songs = songs.paginate(page: page_num, per_page: page_size)
        end

        # https://datatables.net/manual/server-side
        song_data = {
          draw: params[:draw].to_i,
          recordsTotal: Song.count,
          recordsFiltered: records_filtered,
          data: songs
        }

        render json: song_data and return
      end

      format.html do
        return
      end
    end
  end

  def show
    @song = Song.find(params[:id])
    if params[:disable_chords]
      Formatter.format_song_no_chords(@song)
    elsif params[:new_key].present?
      Transposer.transpose_song(@song, params[:new_key])
    elsif params[:numbers]
      Formatter.format_song_nashville(@song)
    end

    @has_been_edited = @song.audits.updates.count.positive?

    respond_to do |format|
      format.html do
        Song.increment_counter(:view_count, @song.id, touch: false)
      end
      format.json do
        render json: @song
      end
    end
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      flash[:success] = "#{@song.name} successfully created!"
      redirect_to @song
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      flash[:success] = "#{@song.name} successfully updated!"
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    if @song.destroy
      flash[:success] = "#{@song.name} successfully deleted!"
      redirect_to songs_path
    else
      logger.info "#{current_user} tried to delete #{@song} but failed"
      flash[:error] = "Unable to delete #{@song.name}"
      redirect_to @song
    end
  end

  def print
    @song = Song.find(params[:id])
    if params[:disable_chords]
      Formatter.format_song_no_chords(@song)
    elsif params[:new_key].present?
      Transposer.transpose_song(@song, params[:new_key])
    elsif params[:numbers]
      Formatter.format_song_nashville(@song)
    end
    render layout: false
  end

  private

  def song_params
    params.require(:song)
          .permit(:name, :key, :artist, :tempo, :bpm, :standard_scan, :chord_sheet, :spotify_uri, :category)
  end
end

app/helpers/songs_helper.rb
# frozen_string_literal: true

module SongsHelper
  def get_tempo_opts(selected, include_any = false)
    options = Song::VALID_TEMPOS.map { |t| [t, t] }
    options.insert(0, ['Any', '']) if include_any
    options_for_select(options, selected:)
  end

  def get_key_opts(selected, include_any = false)
    options = Song::VALID_KEYS.map { |k| [k, k] }
    options.insert(0, ['Any', '']) if include_any
    options_for_select(options, selected:)
  end

  def get_category_opts(selected, include_any = false)
    options = Song::VALID_CATEGORIES.map { |k| [k, k] }
    options.insert(0, ['Any', '']) if include_any
    options_for_select(options, selected:)
  end
end

app/views/songs/_form.html.erb
<%= form_for @song, html: {class: 'form'} do |f| %>
  <% if @song.errors.any? %>
    <div class="song-errors alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <div id="error_explanation">
        <strong><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</strong>
        <ul>
        <% @song.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-6 required <%= highlight_if_errors(@song, :name) %>">
      <%= f.label :name, 'Song Title' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= f.label :artist %>
      <%= f.text_field :artist, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4 required <%= highlight_if_errors(@song, :tempo) %>">
      <%= f.label :tempo %>
      <%= f.select :tempo, Song::VALID_TEMPOS, { prompt: "Choose tempo" }, class: 'form-control' %>
    </div>
    <div class="form-group col-md-4 <%= highlight_if_errors(@song, :bpm) %>">
      <%= f.label :bpm %>
      <%= f.number_field :bpm, in: 1..1000, class: 'form-control' %>
    </div>
    <div class="form-group col-md-4 required <%= highlight_if_errors(@song, :key) %>">
      <%= f.label :key %>
      <%= f.select :key, Song::VALID_KEYS, { prompt: "Choose key" }, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6 <%= highlight_if_errors(@song, :category) %>">
      <%= f.label :category %>
      <%= f.select :category, Song::VALID_CATEGORIES, { include_blank: 'Choose category' }, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :standard_scan, "Standard Scan" %>
    <%= f.text_field :standard_scan, placeholder: "e.g. V1. V2. PC. C. V3. V4.", class: 'form-control' %>
  </div>

  <div class="form-group required <%= highlight_if_errors(@song, :chord_sheet) %>">
    <%= f.label :chord_sheet, "Chord Sheet" %>
    <%= f.text_area :chord_sheet, class: 'fixed-width form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :spotify_uri %>
    <br>
    <i>Open Spotify > Right Click On Song > Share > Hold Option/Alt > Copy Spotify URI</i>
    <%= f.text_field :spotify_uri, placeholder: "e.g. spotify:track:6qdpQ6jPiaCYE9Qw4nZVuD", class: 'form-control' %>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-warning' %>
<% end %>

app/views/songs/_praise_set_song.html.erb
<div class="song row praise-set-song">
  <div class="col-md-12 song_content praise-set-song-content flex-row flex-align-items-center flex-justify-space-between">
    <div class="flex-row flex-align-items-center">
      <%= content_tag :i, class: "fa fa-bars fa-2x drag-handle song_dragIcon l-h-right-spaced" do %>
      <% end %>
      <div class="song-info">
        <div class="song_title"><%= link_to song.name, song, class: "link", target: "_blank" %></div>
        <input type="hidden" name="praise_set[praise_set_songs][][song_id]" value="<%= song.id %>"/>
        <span><strong>Key:</strong> <span class="key"><%= select_tag "praise_set[praise_set_songs][][song_key]", get_key_opts(song.key), class: "form-control input-sm praise-set-song-key" %></span></span>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <span><strong>Tempo:</strong> <%= song.tempo %> <%= "(#{song.bpm} bpm)" if song.bpm %></span>
      </div>
    </div>
    <%= link_to "", class: "remove-song song_trashIcon" do %>
      <i class="fa fa-trash-o fa-2x"></i>
    <% end %>
  </div>
</div>

app/views/songs/_spotify_widget.html.erb
<iframe
  class="spotify-widget"
  allow="encrypted-media"
  src="<%= local_assigns[:widget_source] %>"
></iframe>

app/views/songs/edit.html.erb
<% set_page_title "Edit #{@song.name}" %>

<div class="form-page container">
  <h1>Edit <%= @song.name %></h1>
  <hr>

  <%= render partial: "form" %>
</div>

app/views/songs/history.html.erb
<style>
  <%= Diffy::CSS %>
</style>

<% page_title = @song.name + " Edit History" %>

<% set_page_title page_title %>

<div class="container">
  <h1 class="page-header"><%= page_title %></h1>

  <% @audits.reverse.each do |audit| %>
    <div class="row">
      <div class="col-md-12">
        <h4>Version <%= audit.version %></h4>
        <h5><%= audit_action_past_tense(audit.action).capitalize %> by <strong><%= audit.user.to_s %></strong> at <%= audit.created_at %></h5>

        <br/>

        <% audit.audited_changes.each do |field, diff| %>
          <% split_diff = Diffy::SplitDiff.new(diff[0], diff[1], :format => :html) %>
          <% heading_name = audit.id.to_s + "_" + field + "_heading" %>
          <% field_name = audit.id.to_s + "_" + field %>
          <div class="panel panel-default">

            <div class="panel-heading" role="tab" id="<%= heading_name %>">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" href="#<%= field_name %>" aria-expanded="false" aria-controls="<%= field_name %>">
                  <%= field.humanize %>
                </a>
              </h4>
            </div>

            <div class="panel-collapse collapse" id="<%= field_name %>" role="tabpanel" aria-lablledby="<%= heading_name %>">
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-6 col-xs-12">
                    <h4>Before</h4>
                    <hr/>
                    <%= split_diff.left.html_safe if !split_diff.left.nil? %>
                  </div>
                  <div class="col-md-6 col-xs-12">
                    <h4>After</h4>
                    <hr/>
                    <%= split_diff.right.html_safe if !split_diff.right.nil? %>
                  </div>
                </div>
              </div>
            </div>

          </div>
        <% end %>
        <hr/>
      </div>
    </div>
  <% end %>
</div>

app/views/songs/index.html.erb
<% set_page_title "Songs" %>

<div class="index-page">
  <div class="container">
    <div class="row">
      <div class="center-block">
        <h1>Songs</h1>

        <div class="search">
          <div class="search_input_container">
            <input type="search" id="songs-search-field" class="form-control search_input" placeholder="Search lyrics, song titles, and artists"/>
            <i class="fa fa-search"></i>
          </div>
          <table class="search_filters filter-selection" border="0">
            <tbody>
              <tr>
                <td>
                  <div class="search_filter">
                    <span class="search_filter__label">Key</span>
                    <%= select_tag :key, get_key_opts('Any', include_any = true), class: 'form-control search_filter__form-control' %>
                  </div>
                </td>
                <td>
                  <div class="search_filter">
                    <span class="search_filter__label">Tempo</span>
                    <%= select_tag :tempo, get_tempo_opts('Any', include_any = true), class: 'form-control search_filter__form-control' %>
                  </div>
                </td>
                <td>
                  <div class="search_filter">
                    <span class="search_filter__label">Category</span>
                    <%= select_tag :category, get_category_opts('Any', include_any = true), class: 'form-control search_filter__form-control' %>
                  </div>
                </td>
                <td>
                  <div class="search_filter">
                    <span class="search_filter__label">Sort By</span><%= select_tag :sort, options_for_select(['Relevance', 'Newest First', 'Most Popular First'], 'Relevance'), class: 'form-control search_filter__form-control' %>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <table class="tbl tbl-bottom-spacing songs-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Artist</th>
              <th>Key</th>
              <th>Category</th>
              <th>Tempo</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>

  <div class="preview-drawer">
    <div class="close-button">x</div>
    <div class="title">
      <h1 target="_blank" class="name"></h1>
    </div>
    <a class="pill pill-small pill_link-dark-blue page-link" target="_blank"><i class="fa fa-eye"></i> View Full Page</a>
    <div class="artist"></div>
    <div class="meta-info">
      <div>Key: <span class="key"></span>&nbsp;&nbsp;|&nbsp;&nbsp;Tempo: <span class="tempo"></span></div>
    </div>
    <%= render partial: "spotify_widget" %>
    <div class="chord-sheet fixed-width"></div>
  </div>
</div>

<%= javascript_include_tag 'songs/index' %>

app/views/songs/new.html.erb
<% set_page_title "Upload Song" %>

<div class="form-page container">
  <h1>Upload a Song</h1>
  <hr>
</div>

app/views/songs/print.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @song.name %></title>
  <%= stylesheet_link_tag 'print-songs', media: 'all' %>
</head>
<body>
  <div id="heading">
    <h1 class="title"><%= @song.name %></h1>
    <p>
      <% if @song.artist.present? %>
        <b>Artist:</b> <%= @song.artist %> &nbsp;|&nbsp;
      <% end %>
      <b>Key:</b> <%= @song.key %> &nbsp;|&nbsp;
      <b>Tempo:</b> <%= @song.tempo %> <%= "(#{@song.bpm} BPM)" if @song.bpm.present? %>
    </p>
    <% if @song.standard_scan.present? %>
      <p class="standard-scan"><b>Standard Scan:</b> <%= @song.standard_scan %></p>
    <% end %>
  <br >
  </div>

  <table class="chord-sheet">
    <tr>
      <% Parser.get_lines_for_columns(@song).each do |column_lines| %>
        <td>
          <% column_lines.each do |line| %>
            <% class_for_line = Parser.get_class_for_line(line) %>
            <% if class_for_line == "blank" %>
              <br class=<%= class_for_line %>>
            <% else %>
              <p class=<%= class_for_line %>><%= line %></p>
            <% end %>
          <% end %>
        </td>
      <% end %>
    </tr>
  </table>
</body>
</html>

app/views/songs/search.html.erb
<%= form_tag(search_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Songs" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>
<% if flash.key?(:notice) %>
    <h1> <%= flash[:notice] %> </h1>
<% end %>
<table>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <!--<th>Download</th>-->
    </tr>
    <% @songs.each do |songs| %>
        <tr>
            <td><%= songs.name %></td>
            <td><%= songs.artist %></td>
            <!--<td><%#= download link %></td>-->
        </tr>
    <% end %>
</table>

app/views/songs/show.html.erb
<% set_page_title @song.name %>

<div class="show-page">
  <h1 class="title"><%= @song.name %></h1>
  <div class="artist"><%= @song.artist %></div>
  <div class="buttons-container">
    <%= link_to print_song_path, { method: :get, class: "pill pill_link-dark-blue button-spacing", id: "print-btn", "data-print-url": print_song_path } do %>
      <i class="fa fa-print"></i> Print
    <% end %>
    <% if @has_been_edited %>
      <%= link_to song_history_path, { method: :get, class: "pill pill_link-blue button-spacing" } do %>
        <i class="fa fa-history"></i> History
      <% end %>
    <% end %>
    <% if current_user.can_edit? %>
      <%= link_to edit_song_path, { method: :get, class: "pill pill_link-blue button-spacing" } do %>
        <i class="fa fa-edit"></i> Edit
      <% end %>
    <% end %>
    <% if current_user.can_delete? %>
      <%= link_to @song, { method: :delete, data: { confirm: "Are you sure you want to delete this song?" }, class: "pill pill_link-red button-spacing" } do %>
        <i class="fa fa-trash-o"></i> Delete
      <% end %>
    <% end %>
  </div>
  <% if @song.spotify_uri.present? %>
    <%= render partial: "spotify_widget", locals: { widget_source: @song.spotify_widget_source } %>
  <% end %>
  <div class="song-metadata">
    <span><strong>Suggested Key:</strong> <span class="key"><%= @song.key %></span></span>&nbsp;
    |&nbsp;&nbsp;<span><strong>Tempo:</strong> <%= @song.tempo %></span>
    <% if @song.bpm.present? %>
      <span>(<%= @song.bpm %> BPM)</span>
    <% end %>
    <% if @song.category.present? %>
      <span><strong>Category:</strong> <%= @song.category %></span>
    <% end %>
    <% if @song.standard_scan.present? %>
      <div><strong>Standard Scan:</strong> <%= @song.standard_scan %></div>
    <% end %>
  </div>

  <div class="song-controls">
    <span>Show Chords</span>
    <input id="chords_toggle" checked type="checkbox">
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <span class="transpose-container">View in Key of<%= select_tag :transpose_to, get_key_opts(@song.key), class: "form-control transpose", "data-song-url": song_path(@song, format: :json) %></span>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <span class="to-numbers-container"><%= content_tag :div, "View with Numbers", class: "pill pill_link-dark-blue", id: "to_numbers", "data-song-url": song_path(@song, format: :json) %></span>
    <span class="to-chords-container" style="display:none;"><%= content_tag :div, "View with Chords", class: "pill pill_link-dark-blue", id: "to_chords", "data-song-url": song_path(@song, format: :json) %></span>
  </div>

  <div class="fixed-width chord-sheet "><%= @song.chord_sheet %></div>
</div>

<%= javascript_include_tag 'songs/show' %>