config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/songs')

  resources :songs do
    member do
      get 'print'
    end
  end

  resources :audits, only: [:index]

  get 'songs/:id/history', to: 'audits#song_history', as: 'song_history'

  get "about", to: "general#about"
  get "request_song", to: "general#request_song"

  # Authentication
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: 'sessions#error'
  get 'signout', to: 'sessions#destroy', as: 'sign_out'
  get 'signin', to: 'sessions#new', as: 'sign_in'

  namespace :api, defaults: {format: :json} do
    scope :v1 do
      resources :songs

      scope :audits do
        scope :songs do
          get ':id', to: "audits#song_history"
          get '', to: 'audits#songs_history_index'
        end
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_sign_in

  helper_method :current_user

  # Return a user constructed from the fields stored in the session, nil if one cannot be constructed
  def current_user
    return @current_user if @current_user

    return unless [:user_email, :name, :role].all? { |field| session.key?(field) }

    @current_user = User.new(email: session[:user_email], name: session[:name], role: session[:role])
  end

  def require_sign_in
    redirect_to sign_in_path if current_user.nil?
  end

  def require_edit_privileges
    return if current_user.can_edit?

    flash[:error] = "You don't have edit privileges."
    redirect_to songs_path
  end

  def require_delete_privileges
    return if current_user.can_delete?

    flash[:error] = "You don't have deleting privileges."
    redirect_to songs_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def set_page_title(page_title)
    content_for :title, page_title
  end

  def get_page_title
    [content_for(:title), 'GraceTunes'].compact.join(" | ")
  end

  def alert_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def highlight_if_errors(resource, field_name)
    if resource.errors[field_name].present?
      "has-error"
    else
      ""
    end
  end

  def set_active_if_path(path)
    "header_link-active" if current_page?(path)
  end
end

app/views/application/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> ">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/application/_header.html.erb
<div class="header-container">
  <div class="header">
    <%= link_to root_path, { method: :get, class: "header_logo" } do %>
      Grace<span class="header_logo-emphasized">Tunes</span>
    <% end %>
    <div class="header_links">
      <div class="header_link">
        <%= link_to about_path, { method: :get, class: "#{set_active_if_path(about_path)}" } do %>
          <i class="fa fa-book"></i>About
        <% end %>
      </div>
      <div class="header_link">
        <%= link_to songs_path, { method: :get, class: "#{set_active_if_path(songs_path)}" } do %>
          <i class="fa fa-search"></i>Search
        <% end %>
      </div>
      <div class="header_link">
        <%= link_to audits_path, { method: :get, class: "#{set_active_if_path(audits_path)}" } do %>
          <i class="fa fa-history"></i>Recent Changes
        <% end %>
      </div>
      <% if current_user.can_edit? %>
        <div class="header_link">
          <%= link_to new_song_path, { method: :get, class: "#{set_active_if_path(new_song_path)}" } do %>
            <i class="fa fa-music"></i>Upload Song
          <% end %>
        </div>
      <% end %>
      <div class="header_link">
        <%= link_to request_song_path, { method: :get, class: "#{set_active_if_path(request_song_path)}" } do %>
          <i class="fa fa-music"></i>Request Song
        <% end %>
      </div>
    </div>

    <div class="header_user">
      <span class="header_username">Welcome, <%= current_user.name %>!</span>
      <%= link_to "Sign Out", sign_out_path, { method: :get, class: "pill pill_link-red" } %>
    </div>

  </div>
</div>